server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route 1: Product Service
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/product/**

        # Route 2: Order Service
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/order/**

        # Route 3: Inventory Service
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/inventory/**